### ISSUE TITLE
Select matched text does not work if some other text is already selected

### ISSUE THREAD

**Issue by Lyroxide** [yomidevs/yomitan#1017]
**Description**
With "Select matched text" enabled, if I were to manually highlight some text, then scan a different text, it does not reselect the scanned text.

![image](https://github.com/themoeway/yomitan/assets/33834537/5a40e539-8af7-4ab2-878e-c52bb70508db)

Here I highlighted "漢字の部" manually, then scanned 筆順. I want it to select 筆順 automatically.

**Browser version**
Firefox 126

**Yomitan version**
Yomitan 24.5.21.0

**Comment by khaitruong922** [comment]
It is a feature. 
https://github.com/FooSoft/yomichan/issues/2071
