### ISSUE TITLE
Add term bank reference inSyntaxError; add character reference in ExtensionError

### ISSUE THREAD

**Issue by michel-ZH** [yomidevs/yomitan#1019]
Currently yomitan only tells you which line and column has a syntax error validating dictionary files. It would be nice to also know which term bank this applies to.

**Comment by michel-ZH** [comment]
There are actually two error messages which could be made more verbose:
The issue outlined above
![term_bank_missing](https://github.com/themoeway/yomitan/assets/137377968/84377696-df2e-4506-8240-f983a6d2f4f1)
And the opposite issue, when the file is referenced but not the string causing the issue
![character_reference_missing](https://github.com/themoeway/yomitan/assets/137377968/0c3f47a1-0850-42b3-bcf2-03181c66f4a4)

**Comment by austinyu12** [comment]
Hi, I would like to attempt taking on this issue.

**Comment by austinyu12** [comment]
Hi, I am having trouble recreating a dictionary with bad syntax. Is there a dictionary with bad syntax that could be used to recreate this issue?

**Comment by austinyu12** [comment]
#1462 makes SyntaxError message more verbose. ExtensionError still needs to be made more verbose.

**Comment by austinyu12** [comment]
Modified the ExtensionError message to include `schema.errors`. I wonder if this is fine. I just noticed that there is also a `key` property inside `schema.errors`; Perhaps that is what I should return.
<img width="599" alt="Screenshot 2024-10-07 at 7 46 54 PM" src="https://github.com/user-attachments/assets/7776aac6-9ca8-4d5a-9376-93fd483f54ae">

**Comment by austinyu12** [comment]
Enhancements completed.

**Comment by tomodutch** [comment]
Considering the PR is already merged
https://github.com/yomidevs/yomitan/pull/1473

Is this issue solved?

**Comment by jamesmaa** [comment]
yes
