### ISSUE TITLE
Option to change the encoding of furigana

### ISSUE THREAD

**Issue by ElaineGilstrom** [yomidevs/yomitan#1195]
I've been noticing that it can be quite difficult to add additional formatting (like text color or bold) on top of fields with furigana formatted using the html/ruby tags compared furigana encoded using braces, so I would like to suggest adding an option to change how yomitan does the encoding in options.

Examples of what I mean are these:

html tag formatting:
![image](https://github.com/themoeway/yomitan/assets/23322364/67160aac-3595-4a44-9932-3d07c6649cf1)

brace formatting:
![image](https://github.com/themoeway/yomitan/assets/23322364/6771bc4c-f833-4857-93be-515334d2829b)

what I'm doing with it is adding color to represent pitch accent:
![image](https://github.com/themoeway/yomitan/assets/23322364/8396f57d-5b5f-4130-b9f3-a0f4300f77be)

If this already exists as an option, please let me know. If it doesn't, I can work on adding it in August. I'm not very familiar with node so it might end up taking a bit though.

**Comment by ElaineGilstrom** [comment]
now that I think about it, having auto pitch accent coloring would be awesome too. No idea how much of a pain that would be to implement, but I might look into it.

**Comment by Kuuuube** [comment]
Is there any reason you cant use css selectors for this? You should be able to select the rt tag in the ruby text.

**Comment by ElaineGilstrom** [comment]
That would target all of the furigana, which isn't what I'm after. Each word has its own pitch accent and so needs to have the color that I associate with that pitch accent. 

Here is an example of the intended effect in the card itself:
![image](https://github.com/user-attachments/assets/3aadd546-3bc4-4102-8ad3-2d4312c47758)

**Comment by Kuuuube** [comment]
Are you manually editing the colors? Not sure how this is harder with html as opposed to brackets. It seems like you would be making the exact same additions.

**Comment by ElaineGilstrom** [comment]
I am manually editing the colors, but I am using a plugin to set the color with a hotkey. Because of that, it is significantly less work with the brace encoding as I don't have to make sure the font tags surround the entire span tag, as I do with the html encoded furigana (the plugin also doesn't function in the html editor for the fields)

**Comment by Kuuuube** [comment]
Closing in favor of #1596 being much clearer in intent
