### ISSUE TITLE
Native Browser Window Popup pops to front of screen

### ISSUE THREAD

**Issue by lindseycadwell** [yomidevs/yomitan#1284]
**Description**
I have been using Yomichan/Yomitan to immerse with Text to Speech for almost a year. It used to be the case that as long as I had the popup window not minimized, when I search for a new word, the z-index of the popup window would not change. 

Suddenly in the last couple of days, the popup window is popping to the front of my screen (higher z-index) every time I do a lookup for periods of time, then during other periods, the new behavior is not present. When the z-index of the window changes without my consent like this, my immersion workflow is completely unusable.

Picture of my workflow: 
![image](https://github.com/user-attachments/assets/7a9076ac-c68b-44f6-a2ea-4fbcef205915)

You can see that I need the popup window to stay behind my webnovel's text. When it pops to the front it covers up my text like so:

![image](https://github.com/user-attachments/assets/c938ae69-a20f-4c0e-ba02-589867d6d49b)

I've also noticed that the windows toolbar icon seems to have changed from the yomitan icon to a microsoft edge icon and it's now grouped with my main edge browser window instead of being separate. I'm not sure but I assume whatever caused this change has also caused the issue described above. This change to combine the popup window with my main reading window is also extremely annoying -- but doesn't break my workflow, it just makes switching between discord and immersing take more clicks. Picture:
![image](https://github.com/user-attachments/assets/fbc1a164-a7ec-4150-9271-1e4e673d21c7)

I believe the relevant settings for my reading along with TTS workflow are:
- Select matched text: False
- Use a native browser window instead of an embedded popup: True

I would also love if Yomitan would stop creating brand new popup windows when there's already a popup window open (even if the current popup window is minimized), but that's possibly outside the scope of this issue?

**Browser version**
Microsoft Edge 127.0.2651.74 

**Yomitan version**
24.7.24.0

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page and attach it to this issue.)
[yomitan-settings-2024-07-29-21-01-17.json](https://github.com/user-attachments/files/16419092/yomitan-settings-2024-07-29-21-01-17.json)

**Comment by Kuuuube** [comment]
This doesnt sound like an issue with z-index (at least as far as the webpage can control). But regardless, there are two places total where Yomitan uses variable z-index. Both have not been changed for over 5 months.

The only thing changed recently with window focus is #1194 but that was fixing a somewhat recent regression. It previously functioned that way with focus. If you've been using Yomitan with this workflow for more than about 2 months this also wouldnt be the issue. And if you did develop this workflow that recently it unfortunately only worked because of a bug, not a feature.
