### ISSUE TITLE
Show sentence even if parsing.enableScanningParser is false

### ISSUE THREAD

**Issue by jamesmaa** [yomidevs/yomitan#1370]
Currently yomitan doesn't show the sentence if the parser is turned off
<img width="695" alt="image" src="https://github.com/user-attachments/assets/86d0daa2-9e6a-463a-bead-76086c5951df">
outcome: 
![image](https://github.com/user-attachments/assets/64ed88a7-6cd1-4fa8-a03c-cd4045c717e8)

We should still show the original sentence even if we turn off the sentence parser. This lets users select words within a sentence even if i sentence remains unparsed

related: #1369

**Comment by austinyu12** [comment]
I would like to be assigned this.

**Comment by jamesmaa** [comment]
i don't think anyone's working on this but anyone who wants to can check in here as well

**Comment by austinyu12** [comment]
Been having trouble trying to locate the logic that will update the sentence that is a header on the search page. I think I am on the right path with something like this.
```
async setText(text) {
        if (this._useInternalParser === false && this._useMecabParser === false) {
            return;
        } // all the code from here on can be skipped if no need to parse
        this._text = text;
        this._setPreview(text);

        /** @type {?import('core').TokenObject} */
        const token = {};
        this._setTextToken = token;
        this._parseResults = await this._api.parseText(text, this._getOptionsContext(), this._scanLength, this._useInternalParser, this._useMecabParser);
        if (this._setTextToken !== token) { return; }

        this._refreshSelectedParser();

        this._renderParserSelect();
        this._renderParseResult();
    }
```

**Comment by jamesmaa** [comment]
I think you're in the right file! Feel free to add `console.log` statements or `console.trace` statements or try to walk through this with a debugger to see how it all works. Some documentation on using the debugger https://developer.chrome.com/docs/devtools/javascript#code-stepping
