### ISSUE TITLE
Yomitan cant add words to Anki with AnkiConnect

### ISSUE THREAD

**Issue by WillWoh** [yomidevs/yomitan#1407]
As the title suggests, Yomitan cant add any words/make flashcards to anki with ankiconnect. 
I know ankiconnect works because my browser is able to connect to it, plus Yomitan is able to connect to it as well. But the "+" for adding words is greyed out.
I don't know if anyone can help me out on this or if this is an Ankiconnect side thing

**Browser version**
Version 128.0.6613.120 (Official Build) (64-bit)

**Yomitan version**
24.9.2.0

**Comment by Kuuuube** [comment]
Check your anki card/note configuration. You must have a deck and model selected.

**Comment by brishtibheja** [comment]
Maybe show a pop-up to users communicating what's happening? The current way will leave people confused (we also got a user seeking help in Anki's server about this). What do you think?
