### ISSUE TITLE
Disable scanning on pressing on a link inside a dict (Android)

### ISSUE THREAD

**Issue by shiki-tm** [yomidevs/yomitan#1418]
When touching on a link within a yomitan entry the link is opened plus a 2nd copy popup which is really redundant and inconvenient to close another popup after. I think this only affects mobile or touch screens. I think if disabling scanning on a link is possible it's probably safe to do that for mobile yomitan but I guess maybe some would prefer a toggle setting ?

![Screenshot_20240915_175811_Kiwi Browser](https://github.com/user-attachments/assets/61a80fce-d7b4-4dc9-9bbb-0dfdfa42e0cf)

I know it might not be possible if it's outside of yomitan popup but option to disable scanning on links in general like on websites again for mobile specifically, would also be amazing.

Thanks for quality updates guys

**Comment by Kuuuube** [comment]
Appears to be broken as of version 24.10.7.1. Was supposed to be fixed by #1427 which shipped in version 24.9.23.0.
