### ISSUE TITLE
Add helper-text in recommended dictionaries modal that link to kty's download page

### ISSUE THREAD

**Issue by jamesmaa** [yomidevs/yomitan#1428]
For folks who don't want english dicts

**Comment by fpetrakov** [comment]
@jamesmaa hi, would you mind sharing the mentioned link?

**Comment by jamesmaa** [comment]
@fpetrakov https://github.com/themoeway/kaikki-to-yomitan/blob/master/downloads.md#downloads

**Comment by JackMartinDev** [comment]
@jamesmaa Hi, is this kind of what you have in mind for this feature? Or a more simple one line helper text?

![image](https://github.com/user-attachments/assets/aa2d4e0e-71af-40b6-ab98-11e2af2974aa)

**Comment by jamesmaa** [comment]
This is kind of confusing I would rather put it in small text underneath the recommended dictionary header or as a footnote

**Comment by JackMartinDev** [comment]
@jamesmaa Gotcha, does something like this work?

![image](https://github.com/user-attachments/assets/b6ad2bf6-c7f4-461a-83ff-b69a99c5da1d)

**Comment by jamesmaa** [comment]
yes. this is great. thanks!
