### ISSUE TITLE
{tags} handlebar doesnt return term tags

### ISSUE THREAD

**Issue by fpetrakov** [yomidevs/yomitan#1454]
Hi, is there a way to add the frequency info ("ichi" and "news1k") to the card? I tried both "tags" and all five "frequency" values, but neither of them have this info. Btw, frequency rank and frequency occurance values return `0` or `99999`, which, I guess, are wrong 

![image](https://github.com/user-attachments/assets/49c4cd53-3318-460b-9d5b-9e43d5e86776)
![image](https://github.com/user-attachments/assets/b93e8a12-856e-4e41-8af4-fbbee6a50464)

**Comment by Kuuuube** [comment]
The frequency handlebars are for frequency dictionaries only. Yomitan does not see those as frequency info. Try using `{tags}`.

**Comment by khaitruong922** [comment]
![image](https://github.com/user-attachments/assets/e48a384e-2de9-49ef-80ff-63188d2cecd0)

Looks like `{tags}` only returns the tags within the definitions, not the tags next to the term.

![image](https://github.com/user-attachments/assets/0ce4dad4-46a6-4387-b25a-fdf69cc3826b)

![image](https://github.com/user-attachments/assets/39dbd368-50ce-4af6-8907-2bdaeb658bb1)
