### ISSUE TITLE
Adding "close button" at input bar

### ISSUE THREAD

**Issue by SalwynnJP** [yomidevs/yomitan#1460]
see below
Expected behavior : resets the input I've typed

**Comment by SalwynnJP** [comment]
![image](https://github.com/user-attachments/assets/e277b87d-a6ef-4600-948f-bf1219453688)
![image](https://github.com/user-attachments/assets/db1215e5-b485-4ef0-ac87-39b6ddf73746)

**Comment by tadorituki** [comment]
hi can i be assigned this thanks

**Comment by brishtibheja** [comment]
Didn't auto-close.
