### ISSUE TITLE
Search page is weird

### ISSUE THREAD

**Issue by shiki-tm** [yomidevs/yomitan#1463]
![msedge_VcbcAfGZBd](https://github.com/user-attachments/assets/dea27b59-60a8-4770-bc67-42dc12dedacb)

I notice this on android and PC.  Happens just by clicking on another character/word thats at the top, this big gap is created

**Comment by shiki-tm** [comment]
I cant recreate it on my phone but yeah it just happens like this
https://github.com/user-attachments/assets/a0c3deb1-938a-4c92-87d4-b2b5cab468fe

**Comment by Kuuuube** [comment]
Cant replicate. Send your yomitan settings and browser version.

**Comment by shiki-tm** [comment]
Just noticed it only happens on the chinese profile

[yomitan-settings-2024-10-06-16-32-24.json](https://github.com/user-attachments/files/17270157/yomitan-settings-2024-10-06-16-32-24.json)

Microsoft Edge
Version 129.0.2792.65 (Official build) (64-bit)

お願いします

**Comment by shiki-tm** [comment]
Which yomitan version has this fix? I updated to the one with the new fancy action popup and I was still having this issue on kiwi browser yesterday and probably the day before

**Comment by Kuuuube** [comment]
The first stable release with it is 24.12.03.0. I would recommend updating to the latest though.

**Comment by shiki-tm** [comment]
Yeah that's the one I had the other day.
I don't think edge can be updated any further right..?
![Screenshot_20241212_022210_Edge](https://github.com/user-attachments/assets/7261e67d-36a8-4fe9-8e79-6c6ec72829ac)
 
I'm just on edge canary trying it out because kiwi browser deleted my yomitan.
