### ISSUE TITLE
Wrong て/た-form of some special case verbs

### ISSUE THREAD

**Issue by AdriGrana** [yomidevs/yomitan#1472]
**Issue: Incorrect Recognition of Certain Verb Forms**

### Description
The following verbs have irregular て-forms and past forms:

- 問う → 問うて (not 問って)
- 請う → 請うて (not 請って)
- 乞う → 乞うて (not 乞って)
- 恋う → 恋うて (not 恋って) (here correct form not even recognized)

Yomitan correctly recognizes these exceptions for most verbs, except for **恋う**, where the て-form 恋うて is only labeled as "-te Kansai-ben" rather than also mentioning just "-te." Additionally, Yomitan currently **also** recognizes the incorrect forms (問って, 請って, 乞って, 恋って), which is a mistake.

The same issue applies to their past tense forms:

- 問う → 問うた (not 問った)
- 請う → 請うた (not 請った)
- 乞う → 乞うた (not 乞った)
- 恋う → 恋うた (not 恋った) (here correct form not even recognized)

### Sources for Correct Forms:

1. 三省堂国語辞典　第七版
   - ←と・う【問う】トフ（他五）
   - **〔音便の形は「問うた」 「問うて」〕**

2. **三省堂国語辞典 第七版**
   - こ・う【請う】コフ（他五）
   - **音便の形は「請うた」 「請うて」**
   
3. **三省堂国語辞典 第七版**
   - こ・う【乞う】コフ（他五）
   - **音便の形は「乞うた」 「乞うて」**
   
4. **三省堂国語辞典 第七版**
   - こ・う【恋う】コフ（他五）
   - **音便の形は「恋うた」 「恋うて」**
   
  https://en.wikipedia.org/wiki/Japanese_irregular_verbs 

### Request
Please fix the following:
- Correct the て-form and past form recognition for 恋う (恋うて and 恋うた) to match other verbs of this type.
- Remove recognition of incorrect forms like 問って, 請って, 乞って, and 恋って as well as the past forms.

If there are other verbs with similar exceptions, they should be verified and added to the exception list if necessary.

**Comment by Lyroxide** [comment]
恋う can be fixed but preventing the deinflection of the "incorrect" form is not possible

**Comment by AdriGrana** [comment]
Just out of curiosity, why would it not be possible to prevent the deinflection of the incorrect forms? I think it gives of a bad image of  the software if incorrect forms are kept in Yomitan. But I understand of course that it might be too time consuming to fix this otherwise not so important issue.

**Comment by Casheeew** [comment]
We have considered this problem before, and we have come to the conclusion that these "incorrect" forms should be kept. 

The reasoning for this is because we observed that these "incorrect" forms are used colloquially often enough and it would be helpful for users to still be able to look up these forms.

**Comment by AdriGrana** [comment]
Oh okay if they are a thing colloquially than I don't even consider them incorrect anymore, thanks for the heads up, then I agree that they should be kept. (Though perhaps it good be added to the deinflection that it's not just normal て form but a colloquial version?)
