### ISSUE TITLE
Add option to disabe "add reading" button

### ISSUE THREAD

**Issue by emanuelps2708** [yomidevs/yomitan#1505]
Hi,
I believe it would be helpful to have an option to disable the "Add Reading" button when adding Anki cards. While it's useful for some, I personally don't use it for Japanese, and for languages like German and English, special readings are rarely needed, apart from occasional IPA transcriptions.
![image](https://github.com/user-attachments/assets/8eedad27-2c0d-4c31-b769-37d2b29d61dc)

Thank you!

**Comment by Kuuuube** [comment]
You can remove it with custom css if you want an immediate solution.

**Comment by emanuelps2708** [comment]
Oh great, what would be the css rule?

**Comment by Kuuuube** [comment]
```css
[data-icon="add-term-kana"] {
    display: none;
}
```

**Comment by emanuelps2708** [comment]
It works! thank you ;) 
![image](https://github.com/user-attachments/assets/30b0d51a-c72f-4f50-8f98-7e8db8632353)

**Comment by Kuuuube** [comment]
Closing in favor of #893
