### ISSUE TITLE
Fix Playwright Action Not Erroring

### ISSUE THREAD

**Issue by MarvNC** [yomidevs/yomitan#1529]
https://github.com/yomidevs/yomitan/actions/runs/11447033201/job/31847491075#step:14:20
```
    Error: Timed out 300000ms waiting for expect(locator).toHaveText(expected)

    Locator: locator('id=dictionaries')
    Expected string: "Dictionaries (1 installed, 1 enabled)"
    Received string: "Dictionaries (0 installed, 0 enabled)"
```

For some reason the action still passed, so we need to figure out how to make it fail when that happens.

**Comment by jamesmaa** [comment]
This seems to have been happening before the recommended settings PR https://github.com/yomidevs/yomitan/actions/runs/11278540156/job/31367221529

**Comment by jamesmaa** [comment]
actually I'll create a new issue. This seems slightly different

**Comment by MarvNC** [comment]
Seems the same to me, says 1 flaky at the bottom so it should be caught now.
