### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by Sacus1** [yomidevs/yomitan#1552]
It would be great to have the possibility to choose multiple language at the same time. 
For example, you can be learning Japanese but stumble upon an unknown English word, then it would be great to be able to scan the English word as well.

**Comment by Kuuuube** [comment]
You can already do this you just dont get the deinflection/extra processing.

And quickly switching between settings is what the profiles feature is meant for. You can set it to switch with a hotkey as well.

**Comment by Sacus1** [comment]
Apologies, I wasn’t aware the profiles function was designed to do that.
Thank you for clarifying!
