### ISSUE TITLE
Disable "url" Anki field when creating cards from search page.

### ISSUE THREAD

**Issue by Mar2ck** [yomidevs/yomitan#1558]
The url field is very useful when sentence mining from websites but not at all for the search page. You end up with a useless wall of text on your Anki cards:
![Screenshot_20241102_135703](https://github.com/user-attachments/assets/b11ddd87-2693-4960-bb12-33e76c51ae57)
I think it would be better if this field were left blank when the url starts with `chrome-extension` or `moz-extension`

**Comment by dchen5022** [comment]
Hi, could I be assigned this?
