### ISSUE TITLE
Collapsing a dictionary doesn't take you back to that dictionary 

### ISSUE THREAD

**Issue by shiki-tm** [yomidevs/yomitan#1583]
https://github.com/user-attachments/assets/8c3cc623-6e1d-42e2-9009-0c00ba9461f5

I know this has definitely happened to you before. When looking through long entries, after you finish reading something you just collapse the dictionary to get it out of the way and then everything's lost, you don't know if that entry was up or down. Sometimes it's also accidental on a phone, since we scroll on the far right side of the popup. It's even more confusing when you're actually using yomitan popups, the size of the popup is way smaller, and the video I sent was of the search screen. It's something I've thought about for awhile now but would it be possible to have yomitan send you straight back to the top of the dict entry?

**Comment by SalwynnJP** [comment]
So, I think this is a good "issue" to raise. For now, to scroll, try sticking to the middle to avoid touching the arrows, and when you’ve finished going through a long entry, scroll back up to the dictionary name so you can close it without trouble.

Let’s say the only annoying part is having to scroll back up (for long entries), which does make you lose a bit of time.

**Comment by SalwynnJP** [comment]
We would just need it to close and return to the dictionary name in question.

**Comment by shiki-tm** [comment]
True. I just remember being a yomichan noob and getting confused by this kinda often before
