### ISSUE TITLE
Dictionary ordering seems very unintuitive

### ISSUE THREAD

**Issue by iamllama** [yomidevs/yomitan#1589]
The dictionary ordering ~~/priority~~ system right now seems very misleading, especially for someone who's just gotten into using the extension. 

- What does it mean for an accent dict to be of higher/lower ~~priority~~ ordering than a kanji dict or a normal(?) dict? In the end, the accent dicts get hoisted to the top and the kanji dicts are accessed separately. Unless i'm mistaken and there are dicts that don't just belong to one type (accent, kanji etc.), it doesn't make sense for them to be ordered together.

- The ~~priority~~ ordering doesn't seem to be working for kanji dicts for some reason. I've got `JPDB Kanji` at a higher priority than `KANJIDIC (English)`, but the latter appears before the former for some reason? Again, unless i'm mistaken and doing something wrong here

I understand that it's not everyday that one adds dicts and shuffles them around, but it's always a headache to go back to the list after a while and try to make sense of it 😅

Would be nice to have them grouped by type and then ordered within that type alone

Similar to #796, but focusing more on the unintuitive nature of ~~priorities~~ ordering as things stand and less on clutter

**Comment by iamllama** [comment]
> A dictionary is not restricted to being only a kanji dictionary, term dictionary, frequency dictionary, or accent dictionary. It can have multiple types of kanji/term/tag information within the zip file, as is shown in the official test dictionary.

I was mistaken then. It's unfortunate that generalising it makes it difficult for casual users who are content to use dicts that are, for the most part, of a single type (an assumption)

**Comment by Kuuuube** [comment]
Priorities are legacy settings. You should not use them and they may be removed in a future update. Order your dictionaries using the order they show on the dicts list in settings.

**Comment by iamllama** [comment]
Oh yeah sorry, my prorities are all 0 at the moment. I've gone and conflated them with ordering in the orginal post

![image](https://github.com/user-attachments/assets/c8612388-d4b0-454a-afd2-7f5559e4a800)

The kanji dict ordering problem still happens though

**Comment by khaitruong922** [comment]
Kanji dict ordering will be fixed in #1581
