### ISSUE TITLE
add news ranking to anki card

### ISSUE THREAD

**Issue by indranz** [yomidevs/yomitan#1590]
could the ability to add the news ranking to an anki card be added? it doesn't show up in {tags} or {frequencies].

![Screenshot 2024-11-15 115237](https://github.com/user-attachments/assets/f23d9b1d-0ff3-4efe-80c1-20569be16cea)

**Comment by khaitruong922** [comment]
Have you updated Yomitan? It's already being added in #1464

**Comment by indranz** [comment]
Whoa, great! Sorry, I was on the (older) Firefox version.
