### ISSUE TITLE
On the subject of the schema for frequency meta tags

### ISSUE THREAD

**Issue by precondition** [yomidevs/yomitan#1594]
I'm trying to make sense of https://github.com/yomidevs/yomitan/tree/master/ext/data/schemas/dictionary-term-meta-bank-v3-schema.json in order to better support frequency tags in [Memento](https://github.com/ripose-jp/Memento).  To clarify, I am not looking to create a Yomitan dictionary, I am looking to implement the Yomitan dictionary format in an application that should be able to read and parse any Yomitan dictionary thrown its way.

The JSON schema syntax is very hard to read so can you double-check if my reasoning is correct?

There are 3+ scenarios for the format of a frequency tag in a `term_meta_bank_###.json` file:

1. First scenario:
```json
[
     "<term>","freq",{"reading":"<reading>","frequency":<number>}
 ]
```

Coming from:
```json
{},
{"const": "freq"},
{
    "oneOf": [
          [...snipped irrelevant option...]
        {
            "type": "object",
            "required": [
                "reading",
                "frequency"
            ],
            "additionalProperties": false,
            "properties": {
                "reading": {
                    "type": "string",
                    "description": "Reading for the term."
                },
                "frequency": {
                    "type": "number" // expanded from one of the options in  "$ref": "#/definitions/frequency"
                    "description": "Frequency information for the term."
                }
            }
        }
    ]
}

```

2. Second scenario:
```
[
     "<term>","freq",{"reading":"<reading>","frequency": "<frequency string>">}
 ]
```
Coming from:
```json
{},
{"const": "freq"},
{
    "oneOf": [
          [...snipped irrelevant option...]
        {
            "type": "object",
            "required": [
                "reading",
                "frequency"
            ],
            "additionalProperties": false,
            "properties": {
                "reading": {
                    "type": "string",
                    "description": "Reading for the term."
                },
                "frequency": {
                    "type": "string" // expanded from one of the options in  "$ref": "#/definitions/frequency"
                    "description": "Frequency information for the term."
                }
            }
        }
    ]
}

```

3. Third scenario:
```
[
     "<term>","freq",
     {"reading":"<reading>",
        "frequency": {"value": <number>, "displayValue": "<stylized frequency string>"}
     }
 ]
```
Coming from:
```json
{},
{"const": "freq"},
{
    "oneOf": [
          [...snipped irrelevant option...]
        {
            "type": "object",
            "required": [
                "reading",
                "frequency"
            ],
            "additionalProperties": false,
            "properties": {
                "reading": {
                    "type": "string",
                    "description": "Reading for the term."
                },
                "frequency": {
// start expansion of second option in  "$ref": "#/definitions/frequency"
                    "type": "object",
                    "additionalProperties": false,
                    "required": [
                        "value"
                    ],
                    "properties": {
                        "value": {
                            "type": "number"
                        },
                        "displayValue": {
                            "type": "string"
                        }
                    }
// end expansion of second option in  "$ref": "#/definitions/frequency"
                    "description": "Frequency information for the term."
                }
            }
        }
    ]
}
```

So far, I've been omitting the first `oneOf` option:
```json
{
    "$ref": "#/definitions/frequency",
    "description": "Frequency information for the term."
},
```
so am I understanding correctly that the following scenarios are also possible?

4. Fourth scenario:
```json
[
     "<term>","freq", "<stylized frequency string>"
 ]
```
Coming from:

![image](https://github.com/user-attachments/assets/305f02b7-be24-40f4-8f18-d26daededf50)

5. Fifth scenario:
```json
[
     "<term>","freq", <number>
 ]
```
Coming from
![image](https://github.com/user-attachments/assets/2a97c63c-2d56-4eac-9eb6-6da0ab3cf88e)

6. Sixth scenario:
```json
[
    "<term>","freq",{"value": <number>, "displayValue": "<stylized frequency string>"}
]
```

7. Seventh scenario:
```json
[
    "<term>","freq",{"value": <number>}
]
```
Both coming from:

![image](https://github.com/user-attachments/assets/7fd5719b-f9b3-4249-8a6e-c2899070781d)

with the fact that reading is mandatory but displayValue is optional.

<br>
<br>
<br>

-------

I tried to follow the schema when extending the meta term bank support of Memento in https://github.com/ripose-jp/Memento/pull/237 but I did not realize that the formats such as №6 were legal.
I realized this when coming across this entry from `JPDB_v2.1_kana_2024-05-`26 shared on TMW server:
```json
["アラフォー","freq",{"value":61709,"displayValue":"61709㋕"}]
```
Are there more formats that I am missing?

**Comment by Kuuuube** [comment]
Rather than figure out every possible combination that is accepted in the schema, I think it's better to consider what do you need.

Heres an example of a freq dict `term_meta_bank_1.json` with two terms and has both a value and displayValue:

```json
[["私","freq",{"value":1,"displayValue":"1"}],["言う","freq",{"value":2,"displayValue":"2"}]]
```

**Comment by precondition** [comment]
It is already the second time that I am coming across yet another frequency tag format that requires adding upstream support so I'd rather make sure that I take everything into account this time instead of hurting against the same kind of issue again and again in the future as I use more dictionaries coming from various sources.

**Comment by Kuuuube** [comment]
Ah, I misread. Thought you were creating a dictionary rather than implementing the yomitan format.

How about these cases:

```
[<term>,"freq",{"value":<number>}]
```
```
[<term>,"freq",{"reading":"<reading>","frequency":{"value":<number>}}]
```
