### ISSUE TITLE
Scanning on search page selects first word after space

### ISSUE THREAD

**Issue by Daedalus359** [yomidevs/yomitan#1598]
**Description**
When I use the search page, the scan key does not always select the right word. In particular, it seems to be an issue when scanning parts of dictionary entries containing Japanese text with spaces. The JPDBv2㋕ example sentences and the entirety of [kty-ja-ja](https://github.com/yomidevs/kaikki-to-yomitan/blob/master/downloads.md) entries are two examples. When using shift to select a word in these sections, the selected word is always the first word after the last space prior to what I am really trying to select. See the gif below for examples.

**Browser version**
Chrome Version 131.0.6778.86 (Official Build) (64-bit)

**Yomitan version**
24.11.11.0

**Exported settings file**
[yomitan-settings-2024-11-22-23-43-49.json](https://github.com/user-attachments/files/17877519/yomitan-settings-2024-11-22-23-43-49.json)

![yomitan_scan_error](https://github.com/user-attachments/assets/2f5e0f87-ff20-4361-af46-0a5135506e66)

**Comment by Kuuuube** [comment]
Set scan resolution to `character` instead of `word`, `word` is meant for languages with spaces only. You may need to switch to another language to do this as the option is intended to be disabled on Japanese. This will be fully fixed in #1599.
