### ISSUE TITLE
Search for duplicates doesn't work

### ISSUE THREAD

**Issue by Skretkowicz** [yomidevs/yomitan#1640]
**Description**
My current setup is as follows:
<img width="675" alt="image" src="https://github.com/user-attachments/assets/25251b6e-39c3-4439-87f5-b7c9c0f43d60">
I would like to search for duplicates in my whole collection, so I have chosen options as above

However, when I am looking for a particular word, it shows as if it's not in my collection:
<img width="488" alt="image" src="https://github.com/user-attachments/assets/32a63775-77c2-4bf3-85f7-37b3642a73cf">

Even though when I search for it, I alreadt have card for it in a different decks:
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/e7e013e8-49a0-440f-86f5-bb7199bcd7bb">

Is this a bug or am I doing something wrong?

**Browser version**
133.0

**Yomitan version**
Yomitan 24.11.23.0

**Comment by Kuuuube** [comment]
Make sure the first field on the card in ank is the word. If it's already set like that or doing that didn't fix it, show your full anki fields list for one of the cards added through yomitan.

**Comment by Skretkowicz** [comment]
Hello,

I tried your option first but it did not work for me, However, what has worked is changing the name of the field to "Expression" - I tested in on two decks and both times it started to show only after this change. I believe it's worth highligting in the documentation because current wording in Setting can be confusing

**Comment by Kuuuube** [comment]
The name of the card's fields in anki does not matter.

**Comment by Skretkowicz** [comment]
Maybe it made some kind of refresh then? I only showed after I updated the name

**Comment by Kuuuube** [comment]
You might've had outdated anki settings in yomitan. They will update if you mess with anything under `Configure Anki card template` but nothing is automatically set.

Closing this as it is resolved.

**Comment by Skretkowicz** [comment]
I resteted it, for some reason it does matter:

When the field is on the first place but called like in the original deck, "VocabKanji" it doesn't show:
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/80c1c165-2d21-4847-925d-675c92d70488">

When I change the name to "Expression", it shows immediately:
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/5b172c08-596c-4951-a903-3eff6efd3463">

**Comment by Kuuuube** [comment]
"First field" and "sort field" do not mean the same thing. I'm looking at a screenshot where the first field is `SentKanji` (not `VocabKanji`) and a second screenshot where the first field is `Expression`.

**Comment by Skretkowicz** [comment]
That screenshot may have been confusing, I uploaded the first sceeenshot to show you that the deck "単語N5" does not show when there is no "Expression" field

But again, as soon as I change the name of "expression" field in my deck "core 10k" and "単語N5" they are not recognized anymore when looking for duplicates, only my main mining deck is recognized:

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/5a93d263-611e-4c52-b7d4-bf74377a234d">

**Comment by Kuuuube** [comment]
Show the fields for every note type youre trying to use. And open the raw html part on the first field of them (the `<>` button).
