### ISSUE TITLE
Certain frequency lists break Yomitan

### ISSUE THREAD

**Issue by mjauvi** [yomidevs/yomitan#1650]
**Description**
I've used Yomitan for years with these same frequency lists, but today when I tried scanning words, the popup only showed this
![image](https://github.com/user-attachments/assets/c2aa17ee-2a04-496e-b173-0b4c2bd6e57f)

I went and toggled dictionaries off, but nothing changed. I then toggled off frequency lists, and all but one of the lists make the popup break like this. The popup works normally if those specific lists aren't enabled.

The lists are:

[アニメとドラマの頻度リスト.zip](https://github.com/user-attachments/files/18082517/default.zip)
[Corpus_Narou_Freq.zip](https://github.com/user-attachments/files/18082518/Corpus_Narou_Freq.zip)
[Corpus_VN_Freq.zip](https://github.com/user-attachments/files/18082519/Corpus_VN_Freq.zip)

**Browser version**
Chrome  131.0.6778.109

**Yomitan version**
24.12.03.0

**Comment by Kuuuube** [comment]
Can't replicate. Export and send your settings. Also try resetting your settings and testing again.

**Comment by mjauvi** [comment]
Sure, here are my settings.
[yomitan-settings-2024-12-10-16-42-24.json](https://github.com/user-attachments/files/18082955/yomitan-settings-2024-12-10-16-42-24.json)

**Comment by mjauvi** [comment]
I reset my settings and the problem still persisted.
This is the error that appears in console whenever scanning fails btw
![image](https://github.com/user-attachments/assets/2d341226-bdee-4111-bc03-db3258df3ad9)
