### ISSUE TITLE
Automatic Highlighting of Known/Mined Words.

### ISSUE THREAD

**Issue by SpazzTL** [yomidevs/yomitan#1666]
The ability for Yomitan to auto highlight words previously mined in Anki, maybe with different colors for New, Learning, Known/Mature. Should be a toggle option.

I do realize this might be a bit of a stretch for Yomitan to support, I just don't know how to parse ~~Korean~~ text like Yomitan does and make an extension... yet.

Example:

![image](https://github.com/user-attachments/assets/909d2685-6f23-4051-9a65-bd5b7a20da68)
Green means Learned/Known/Mature
Pink-ish means New
Blue means Learning

The word status can be pulled from Anki

**Comment by brishtibheja** [comment]
Is this a duplicate of https://github.com/yomidevs/yomitan/issues/1578?

**Comment by SpazzTL** [comment]
> * Is this a duplicate of [keep track of words knowledge #1578](https://github.com/yomidevs/yomitan/issues/1578)?

It would appear so.
