### ISSUE TITLE
Yomitan Errors on Firefox Mobile

### ISSUE THREAD

**Issue by icebarf** [yomidevs/yomitan#1674]
**Description**
The extension appears to works fine however, there `!!` symbols on the Extension which says `Yomitan - Errors !!`. It appears randomly on my phone, when using the debugger I get the following text:
<details>
<summary>Error Log from debugger</summary>
<br>

```
Yomitan Popup Dictionary 24.12.10.2 has encountered a problem.
Originating URL: moz-extension://2d55796c-c158-4508-ab86-9c9bea27dca9/background.html
TypeError: chrome.contextMenus is undefined
_applyOptions@moz-extension://2d55796c-c158-4508-ab86-9c9bea27dca9/js/background/backend.js:1336:17
_prepareInternal@moz-extension://2d55796c-c158-4508-ab86-9c9bea27dca9/js/background/backend.js:289:18

Issues can be reported at https://github.com/yomidevs/yomitan/issues [log.js:138:35](moz-extension://2d55796c-c158-4508-ab86-9c9bea27dca9/js/core/log.js)
Yomitan Popup Dictionary 24.12.10.2 has encountered a problem.
Originating URL: moz-extension://2d55796c-c158-4508-ab86-9c9bea27dca9/background.html
TypeError: chrome.contextMenus is undefined
_applyOptions@moz-extension://2d55796c-c158-4508-ab86-9c9bea27dca9/js/background/backend.js:1336:17
_saveOptions@moz-extension://2d55796c-c158-4508-ab86-9c9bea27dca9/js/background/backend.js:2470:14

Issues can be reported at https://github.com/yomidevs/yomitan/issues
```
</details>

I do not know if the `chrome.contextMenus` property is harmful or not, considering the extension seems to work fine. I'm reporting it just-in-case if future issues arise from this.

There were a lot more errors showing up in the console when I was trying out earlier today but they seem to have automagically gone away once I begun writing the report. I cannot reproduce them after multiple tries.

**Browser version**
Mozilla Firefox 133.0.3

**Yomitan version**
24.12.10.2
Android

> A couple months earlier, the extension simply refused to work on firefox for reasons unknown to me. However, after reinstalling the browser, and the extension - It appears to work fine but with those errors I mentioned.

**Comment by Kuuuube** [comment]
All errors from context menus are handled gracefully so nothing should ever break from them not working.

But I can add a check for chrome.contextMenus existing to get rid of the error here.

**Comment by icebarf** [comment]
thanks! closing
