### ISSUE TITLE
Yomitan Does Not Check Duplicates Across Collection.

### ISSUE THREAD

**Issue by cunat999** [yomidevs/yomitan#1702]
Extension version: Yomitan Popup Dictionary 24.12.18.1
Platform: Windows
Browser: Edge
Language: en-US
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
AnkiConnect version: 6

(https://github.com/user-attachments/files/18259453/yomitan-settings-2024-12-27-09-51-15.json)
![image](https://github.com/user-attachments/assets/3e57121d-4062-4d7d-b102-0156b46d64ef)
[yomitan-settings-2024-12-27-09-51-15.json](https://github.com/user-attachments/files/18259470/yomitan-settings-2024-12-27-09-51-15.json)

**Comment by cunat999** [comment]
![image](https://github.com/user-attachments/assets/5216ae76-fc60-4634-8d8d-d27d0e3faa68)
The word 冷 is already added, but still showing

**Comment by cunat999** [comment]
> Member
> ###

![image](https://github.com/user-attachments/assets/dafa6623-df57-42c2-a075-0444b272d6fa)

Hello, they both showing "冷", the same word 冷.
I don't know why this morning it's detecting duplicates properly now.

**Comment by cunat999** [comment]
I think I have found the problem, it has added {expressions} in the Front field.
But somehow, it got a few spacebar after the {expressions}, making the Front field differs.

How to potentially fix this? Thank you!

**Comment by Kuuuube** [comment]
Reset your handlebars. This is a very common issue if you've edited your handlebars.

If you've created a large amount of cards with this issue, there are anki addons that can do a bulk replace to remove those spaces.

**Comment by cunat999** [comment]
> Reset your handlebars. This is a very common issue if you've edited your handlebars.
> 
> If you've created a large amount of cards with this issue, there are anki addons that can do a bulk replace to remove those spaces.

Thank you very much, may I know what is that Anki Addons?

**Comment by cunat999** [comment]
> Reset your handlebars. This is a very common issue if you've edited your handlebars.
> 
> If you've created a large amount of cards with this issue, there are anki addons that can do a bulk replace to remove those spaces.

Thank you very much, may I know what is that Anki Addons?

**Comment by Kuuuube** [comment]
https://ankiweb.net/shared/info/291119185

Make sure to create a backup before using it.
