### ISSUE TITLE
Change "Statistics" placement of kanji dicts 

### ISSUE THREAD

**Issue by eurusdagr** [yomidevs/yomitan#230]
Unfortunately it seems this is hard coded into yomichan as it can't be changed by the user, it would rather be better if the "Statistics" part be put as the same level as the "Classifications" or "Codepoints" since it can become very cramped(see image)
![image](https://github.com/themoeway/yomitan/assets/82729967/1c19a31d-b437-4cd6-a49a-923847da9b23)

**Comment by Kuuuube** [comment]
Closing in favor of #596
