### ISSUE TITLE
Sentence scanning to include image alt text (e.g. emoji)

### ISSUE THREAD

**Issue by toasted-nutbread** [yomidevs/yomitan#467]
Emoji are sometimes used in writing or communication, but the sentence scanning functionality ignores them, so this context will be truncated when added to Anki cards. Could potentially be nice to support this if it doesn't add significant complexity. On the other hand, it's not as trivial as it may seem, since most emoji are composed of UTF16 surrogate pairs. Anyway, just an issue to put on the radar.

**Comment by Scrub1492** [comment]
seems to be working fine for me
![image](https://github.com/themoeway/yomitan/assets/52880648/2c530d79-bdfa-4c90-b196-e48722a4ae3d)
![image](https://github.com/themoeway/yomitan/assets/52880648/99597b96-47ae-4b6c-99a3-c7ff9e5e7140)

**Comment by toasted-nutbread** [comment]
So I think it does work when normal emoji are used, which I didn't actually test because I forgot that websites will often replace them with their own custom emoji, take discord for example:

```
<img aria-label="💀" src="https://discord.com/assets/71e7a2f93eca777dc211.svg" alt="💀" draggable="false" class="emoji" data-type="emoji" data-name=":skull:">
```

#359 is also related

So basically including image alt text in scans would be useful.
