### ISSUE TITLE
Scanning doesn't work on Calibre content server's web-reader in Firefox

### ISSUE THREAD

**Issue by radonmiser** [yomidevs/yomitan#499]
**Description**
Works on chrome, not Firefox, other browsers not tested.
to reproduce:
1. enable content server on Calibre
2. scan a book's text in chrome
with these 2 options configured yomitan behaves normally on the web-reader in chrome
![image](https://github.com/themoeway/yomitan/assets/61794107/9b3efe73-84dd-4c48-be8b-4d118d276bc1)
![image](https://github.com/themoeway/yomitan/assets/61794107/c0b936c1-7f3b-42ea-9df9-595cabffc9a6)
3.in Firefox the popup doesn't show up at all

**Browser version**
FF 121.0
**Yomitan version**
23.11.23.0

**Exported settings file**
(If you think it might be relevant, create a settings export file using the _Export Settings_ button on the settings page; zip or rename the resulting file to .txt to attach to the issue.)

**Comment by radonmiser** [comment]
update: It stopped working on chrome as well
Version 124.0.6367.119 (Official Build) (64-bit)
same steps to reproduce, the text in Calibre's reader stopped being scanned.

**Comment by zegalur** [comment]
I am experiencing the same issue on both Chrome and Firefox. 
The problem is due to the book content being wrapped in an `iframe` with a non-empty `sandbox` attribute.

Minimal HTML to reproduce the issue:
```html
<!DOCTYPE html>
<html lang="ja">
<head><meta charset="utf-8"></head>
<body>
  テレビです
<iframe 
   sandbox="allow-popups allow-scripts allow-popups-to-escape-sandbox" 
   srcdoc="<!DOCTYPE html><html lang='ja'><head><meta charset='utf-8'></head><body>テレビです</body></html>">
</iframe>
</body>
</html>
```

Workaround:
In the `[Calibre Foulder]/app/resources/content-server/index-generated.html` comment out the `sandbox` line:
```js
iframe_kw = (function(){
    var ρσ_d = Object.create(null);
    ρσ_d["id"] = iframe_id;
    ρσ_d["seamless"] = true;
    //ρσ_d["sandbox"] = "allow-popups allow-scripts allow-popups-to-escape-sandbox";
    ρσ_d["style"] = "flex-grow: 2";
    ρσ_d["allowfullscreen"] = "true";
    return ρσ_d;
}).call(this);
```

**Comment by Kuuuube** [comment]
This not working appears to be intentional by browsers as a security feature.
