### ISSUE TITLE
Display descriptions and metadata of the dictionaries when clicking dictionary tag in popup

### ISSUE THREAD

**Issue by ganqqwerty** [yomidevs/yomitan#570]
Various metadata like description and the size of the dictionary can be displayed on hover on the dictionary marker.

**Comment by toasted-nutbread** [comment]
Assuming this is in reference to the popup: Hover is not present on all devices. Should probably use a notification message on tap similar to what clicking on the tags already does.

**Comment by ganqqwerty** [comment]
Yes, fair enough. Right now when a user clicks on a pill of the frequency dictionary, the small notification message appears. This sounds like an obvious place for the description/metadata of that dictionary.
