### ISSUE TITLE
Use 2 spaces for tabs instead of 4

### ISSUE THREAD

**Issue by toasted-nutbread** [yomidevs/yomitan#676]
As I'm coming to the end of all of the eslint update stuff I'm trying to do, something has stuck out to me about this codebase for a while, going back to the Yomitan era.

1. 4 spaces are used for tabs rather than 2. IMO 2 looks better and also reduces file size, sometimes significantly, and 2 feels like more of a modern style for JS/TS. For a few of the data JSON files, these are already overridden to 2-space tabs to reduce their file size. Thoughts on 4 vs 2 space indent?

**Comment by MarvNC** [comment]
+1 for two spaces and trailing commas.

**Comment by Scrub1492** [comment]
4 space tabs feel better to me as its slightly easier to view, and also creates a mental block on writing unnecessarily complex nested code. But either way is good.

**Comment by djahandarie** [comment]
Definitely would prefer having the trailing commas for the exact reason you mention.

As for tab size, I don't care much and I think either way is fine. If there's lots of agreement that 2 spaces is better that I don't see why we shouldn't change it (expect maybe that it'd make git blame harder to use effectively).

**Comment by toasted-nutbread** [comment]
I mean realistically, you can probably blame me for almost everything that breaks in the codebase anyways, so it's not like the blame situation would be that much different.

But jokes aside, I can implement trailing commas at least, and provide a sample PR of what 2 space indent would look like so we can see if there's anything strongly for or against that comes from that.

**Comment by jamesmaa** [comment]
Going to split this into two issues because one of these decisions is controversial and the other isn't and ready to be implemented

**Comment by Kuuuube** [comment]
Closing as this has been discussed previously and was determined not worth destroying the blame log. (also i will fight anyone who thinks 2 is better than 4)
