### ISSUE TITLE
Yomitan Popup Closes When Hovering Over Child Popup + "Hide popup on cursor exit" bugged

### ISSUE THREAD

**Issue by wwly23** [yomidevs/yomitan#689]
**Description**

Whenever I hover over a child popup when looking up a word in a J-J dictionary for example both popups close. This is with Hide popup on cursor exit enabled.
24.01.14.0 (Chrome) - 24.2.12.0 (Firefox) Bugged in both.

When I unchecked Hide popup on cursor exit for troubleshooting purposes, hovering over the child popup no longer closes both popups. However, there's a bug where the parent popup still closes after I move the cursor out of the parent window using 24.2.12.0 (Firefox). Seems to be okay on 24.01.14.0 (Chrome) I think.

All of the above was tested with Auto-hide search popup set to On. When I disabled that everything works as expected (only closes after I click away). I'm not sure if I understand the difference between the difference between Auto-hide search popup and Hide popup on cursor exit. I put the delay for both settings to 100ms if that helps.

**Browser version**
Latest Firefox/Chrome as of February 14th

**Comment by StefanVukovic99** [comment]
related: #493
