### ISSUE TITLE
Redundant escaping is still an issue

### ISSUE THREAD

**Issue by globalchubby** [yomidevs/yomitan#856]
What version of the extension was #722 supposed to be deployed on?

<img width="474" alt="image" src="https://github.com/themoeway/yomitan/assets/2729079/7d693202-2284-488f-83f0-7a11c960f92a">

I have Yomitan 24.4.16.0 running on Brave 1.65.114 Chromium: 124.0.6367.60 (Official Build) (x86_64) and it's still an issue.

![image](https://github.com/themoeway/yomitan/assets/2729079/8ff1d755-8159-44ea-937c-085f7afa7bd7)

![image](https://github.com/themoeway/yomitan/assets/2729079/c0edec6f-7e67-4e60-b74e-346c461b66ce)

**Comment by Kuuuube** [comment]
This should have been fixed since [24.4.7.0](https://github.com/themoeway/yomitan/releases/tag/24.4.7.0)

Which handlebar are you using for that field? It might also be helpful if you can provide your full handlebars code under `Configure Anki Card Templates...` (copy paste into a txt file and upload).

**Comment by Kuuuube** [comment]
Looked into this a bit and it seems to be the same issues as #686 just with a different handlebar. Theres a few handlebars having this issue right now.

**Comment by Kuuuube** [comment]
You dont have to wait for the update to fix these, just replace any of the following handlebars youre using with the new ones under `Configure Anki Card Templates...`:

```
{{#*inline "sentence"}}
    {{~#if definition.cloze}}{{{definition.cloze.sentence}}}{{/if~}}
{{/inline}}
```
```
{{#*inline "cloze-prefix"}}
    {{~#if definition.cloze}}{{{definition.cloze.prefix}}}{{/if~}}
{{/inline}}
```
```
{{#*inline "cloze-body"}}
    {{~#if definition.cloze}}{{{definition.cloze.body}}}{{/if~}}
{{/inline}}
```
```
{{#*inline "cloze-body-kana"}}
    {{~#if definition.cloze}}{{{definition.cloze.bodyKana}}}{{/if~}}
{{/inline}}
````
```
{{#*inline "cloze-suffix"}}
    {{~#if definition.cloze}}{{{definition.cloze.suffix}}}{{/if~}}
{{/inline}}
```

**Comment by yangmillstheory** [comment]
Thanks. If I implement https://github.com/themoeway/yomitan/issues/856#issuecomment-2072372237, will it conflict with the changes introduced by #857? If so, I'd rather wait for the true fix.

**Comment by Kuuuube** [comment]
No, handlebars updates work by find and replace. If it can't find the broken handlebar to replace (you've already replaced it yourself) it can't replace a second time so there's nothing for it to break.

**Comment by yangmillstheory** [comment]
Will the proposed solution work if I'm using `{clipboard-text}`?

<img width="635" alt="image" src="https://github.com/themoeway/yomitan/assets/2729079/aa279576-c04f-44af-a19d-e26c54231f62">

I'm trying out the solution, but I don't see `{clipboard-text}` in https://github.com/themoeway/yomitan/issues/856#issuecomment-2072372237. I'm not a Handlebars expert by any means.
