### ISSUE TITLE
Jitendex just won't Import

### ISSUE THREAD

**Issue by JmDictInVain** [yomidevs/yomitan#880]
**Description**
Yomitan keeps crashing everytime I try to install this dictionary. I am using a samsung sm-t510 and it just won't let me import it. Every other dictionary is fine but Jitendex just won't install. Crashes always.

**Browser version**
Kiwi Browser 124.0.6327.4

**Yomitan version**
Yomitan v24.4.16.0

**Comment by MarvNC** [comment]
Related: #381 #863
