### ISSUE TITLE
Better Support for Media Content

### ISSUE THREAD

**Issue by ghost** [yomidevs/yomitan#881]
Yomitan does an amazing job with text-based materials. However, when it comes to media content, the situation is less than ideal, as it requires a third-party extension to function. Unfortunately, these third-party extensions often end up breaking Yomitan's functionality. Additionally, platforms like Netflix only provide hard-coded subtitles, requiring a third-party extension to make the Yomitan functional.

My point here is that the majority of users primarily utilize Netflix and YouTube for media content. Since it requires a third-party extension to utilize Yomitan with those platforms, and those extensions will most likely work improperly, it could be beneficial to support these platforms as accessibility options, similar to how Google Docs is supported.

![image](https://github.com/themoeway/yomitan/assets/103891807/ab66e25c-871a-4a82-bc27-dcfa074c385a)

For example, if transliteration is activated for Chinese with Language Reactor, Yomitan is unable to scan the text. Another example would be the inability to properly extract sentences when I have transliteration activated. https://github.com/themoeway/yomitan/issues/560

https://github.com/themoeway/yomitan/assets/103891807/94c04a0d-e6ca-411a-816f-6d7a77696385

Expected Features:

Since the main languages utilized with Yomitan are Japanese and Chinese, which often require transliteration, it would be helpful if Yomitan could provide transliteration and make the text selectable.

If addressing this issue is beyond the scope of the project, please feel free to close the issue.

**Comment by Kuuuube** [comment]
This is not a yomitan issue. Also related #1185
